apiVersion: apps/v1
kind: Deployment
metadata: 
  name: basic-ci-cd
spec: 
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: basic-ci-cd
  
  template:
    metadata:
      labels:
        app: basic-ci-cd

    spec:
      containers:
      - name: basic-ci-cd
        image: phutawan1906/myapp:d61b4749919fd947c864fcfa056da20072e6a8ca
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
